openapi: 3.0.3
info:
  title: Employee Service API
  description: API documentation for Employee Database
  version: 1.0.0
servers:
  - url: 'https://localhost:8100'
paths:
  /employees:
    get:
      tags:
        - Employee
      operationId: getAllEmployees
      summary: Get all employees
      security:
        - basicAuth: []
      parameters:
        - name: role
          in: header
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 50
            enum:
              - ADMIN
              - USER
              - MANAGER
      responses:
        '200':
          description: List of all employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - Employee
      operationId: createEmployee
      summary: Create a new employee
      security:
        - basicAuth: []
      parameters:
        - name: role
          in: header
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 50
            enum:
              - ADMIN
              - USER
              - MANAGER
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /employees/{id}:
    get:
      tags:
        - Employee
      operationId: getEmployee
      summary: Get employee details by ID
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: role
          in: header
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 50
            enum:
              - ADMIN
              - USER
              - MANAGER
      responses:
        '200':
          description: Employee found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Employee
      operationId: updateEmployee
      summary: Update employee details
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: role
          in: header
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 50
            enum:
              - ADMIN
              - USER
              - MANAGER
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: Employee updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Employee
      operationId: deleteEmployee
      summary: Delete an employee
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: role
          in: header
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 50
            enum:
              - ADMIN
              - USER
              - MANAGER
      responses:
        '200':
          description: Employee deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: Employee deleted successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /roles/{id}:
    delete:
      tags:
        - Role
      operationId: deleteRole
      summary: Delete a role
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Role deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: Role deleted successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Role not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /{employeeId}/projects/{projectId}:
    put:
      tags:
        - Project
      operationId: assignProjectToEmployee
      summary: Assign a project to an employee
      security:
        - basicAuth: []
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Project assigned to employee successfully
          content:
            application/json:
              schema:
                type: string
                example: Project assigned to employee successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee or Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Employee:
      type: object
      required:
        - firstname
        - surname
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
          minLength: 1
          maximum: 50
          pattern: "^[A-Za-z]+$"
          example: John
        surname:
          type: string
          minLength: 1
          maxLength: 50
          pattern: "^[A-Za-z]+$"
          example: Doe
        role_id:
          type: integer
          format: int64
        project_ids:
          type: array
          items:
            type: integer
            format: int64
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        detailedMessage:
          type: string